import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const data = new Date()

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='flex flex-col justify-start gap-4 p-20 items-center min-h-screen'>
        
        <header className="bg-gradient-to-r from-indigo-600 to-purple-600 text-white shadow-xl sticky top-0 z-50">
          <nav className="max-w-7xl mx-auto px-6 py-5 flex justify-between items-center">
            <Link href="/" className="text-2xl font-bold hover:text-cyan-300 transition">
              React & Next.js
            </Link>

            <ul className="flex gap-10 text-lg font-medium">
              <li>
                <Link href="/" className="hover:text-cyan-300 transition">
                  Início
                </Link>
              </li>
              <li>
                <Link href="/sobre" className="hover:text-cyan-300 transition">
                  Sobre
                </Link>
              </li>
              <li>
                <Link href="/caracteristicas" className="hover:text-cyan-300 transition">
                  Características
                </Link>
              </li>
              <li>
                <Link href="/tecnologias" className="hover:text-cyan-300 transition">
                  Tecnologias
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        
        <main className="bg-blue-200 p-5 rounded-2xl max-w-2xl min-h-[70vh]">
          {children}
        </main>
        
        <footer>{data.getFullYear()}</footer>

      </body>
    </html>
  );
}
